### ISSUE TITLE
Make better timestamps on VRPN Streaming Arduino server

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Latent#1]
It looks like the data from the arduino comes in bursts, so we should back-date the measurement time by the transmission delay for the number of characters in the buffer when that report was parsed from the time that the read returned the block of characters

**Comment by russell-taylor** [comment]
Fixed in commit e23aa0ed6fffed647a198f31bffa1fbe8f36c8ff on the VRPN master branch.

**Comment by balajyothi** [comment]
Hi Russell,

Can I have query on your blog regarding PNI sensor.

**Comment by balajyothi** [comment]
Even I need to interface the PNI sensor for 3DOF with arduino ,can you help me on this.

**Comment by russell-taylor** [comment]
The VRPN streaming Arduino server should let you read from sensors plugged into analogs, but it won't help with sensors that are read by other means.  It might be an example that could help you build such a thing.

**Comment by balajyothi** [comment]
Hi Russell,

Thanks for the reply.

I need help the sensors reading data using arduino only.

On Mon, Sep 28, 2015 at 5:35 PM, Russell Taylor <notifications@github.com>
wrote:

> The VRPN streaming Arduino server should let you read from sensors plugged
> into analogs, but it won't help with sensors that are read by other means.
> It might be an example that could help you build such a thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReliaSolve/Latent/issues/1#issuecomment-143724954>.
>



-- 


   Regards,


   Mrs.V.B.N.Jyothi,
   Scientist-C,DST,
      NIOT,Chennai,India
         Ph:9940640947
